services:

  traefik:    
    build:
      context: ./traefik
      dockerfile: Dockerfile

    restart: always
    hostname: traefik
    ports:      
      - target: 443
        published: 443
        mode: host
     
    volumes:
      - traefik-certificates:/certificates

    secrets:
      - letsencrypt-email     

    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL_FILE=/run/secrets/letsencrypt-email
    
    networks:
      - traefik-public
  
  utiutiuti:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    hostname: utiutiuti
    restart: always
    networks:
      - traefik-public
    
volumes:
  traefik-certificates:

networks:  
  traefik-public:    

secrets:
  letsencrypt-email:
    file: letsencrypt-email.txt
